### ISSUE TITLE
Lost Identity api when updating to ASP.NET Core 2.1 to 2.2

### ISSUE THREAD

**Issue by Xarkam** [aspnet/AspNetCore#6377]
### Describe the bug
Today, I upgraded my projects to netcoreapp 2.1 to 2.2.
After that, my projects using `Microsoft.AspNetCore.Identity` give me an error:
`error CS0234: The name or namespace name 'Identity' does not exist in the 'Microsoft.AspNetCore' namespace (are you missing an assembly reference?)`

**note before reproduce :** 
- if I add the Microsoft.AspNetCore.Identity nuget package in project reference, I don't have any error with using directive, but I have always error on cannot found `IdentityUser`
- I also cleaned nuget cache on my machine

**If I back to 2.1.x version, I have not problems with Identity**

### To Reproduce
1. Clone this repos: https://github.com/SOFTINUX/Base
2. restore packages
3. restore npm packages in barebone project
3. make build.

### Expected behavior
Just use Identity api.

### Screenshots
![image](https://user-images.githubusercontent.com/331816/50681499-04efff00-100c-11e9-83bc-52179d0170d6.png)
![image](https://user-images.githubusercontent.com/331816/50681786-040b9d00-100d-11e9-9ed5-a45a37b5aa8f.png)

### Additional context
```
SDK .NET Core (reflecting all the global.json) :
 Version:   2.2.101
 Commit:    236713b0b7

Runtime environment :
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.101\

Host (useful for support):
  Version: 2.2.0
  Commit:  1249f08fed

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.1.502 [C:\Program Files\dotnet\sdk]
  2.2.100 [C:\Program Files\dotnet\sdk]
  2.2.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**edit:** update dotnet core informations.

**Comment by Xarkam** [comment]
I received an answer on https://stackoverflow.com/questions/54039311/lost-identity-api-when-updating-to-asp-net-core-2-1-to-2-2?noredirect=1#comment94915662_54039311

**Comment by blowdart** [comment]
As you have an answer I'm closing this. I assume your source repo is working, so we can't look at what any problem might have been
