### ISSUE TITLE
IHubProtocol.d.ts(1,1): error TS2688: Build:Cannot find type definition file for 'node'.

### ISSUE THREAD

**Issue by yllongboy** [aspnet/AspNetCore#8984]
### Describe the bug
after updating aspnet/signalr to 1.1.2, my project now fails to build due to the error below.
There were no changes in my code except the update of signalr. Even reverting back to old version still throws the same error.

> node_modules\@aspnet\signalr\dist\esm\IHubProtocol.d.ts(1,1): error TS2688: Build:Cannot find type definition file for 'node'.

**Comment by yllongboy** [comment]
Resolved!

It turns out VS 2017 is doing the compile for all ts files. I had it disabled by adding 'TypeScriptCompileBlocked' in my csproj file.

<PropertyGroup>
   <TypeScriptCompileBlocked>true</TypeScriptCompileBlocked>
</PropertyGroup>

Cheers!
