### ISSUE TITLE
Namespace of PageDisplay.cs

### ISSUE THREAD

**Issue by aybelanov** [aspnet/AspNetCore#11240]
### Describe the bug
The PageDisplay.cs is situated in Layouts Folder (Microsoft\AspNetCore\Components\Layouts ) but its namespace is Microsoft.AspNetCore.Components (without Layouts). I create a custom router. If I point Microsoft.AspNetCore.Components.Layouts namespace then I have the compile error "error CS0103: The name 'PageDisplay' does not exist in the current context". When I point  Microsoft.AspNetCore.Components namespace I cannot compile the project at all because I have "CS0234	The type or namespace name 'PageDisplay' does not exist in the namespace 'Microsoft.AspNetCore.Components' (are you missing an assembly reference?)". What I do wrong?

**Comment by aybelanov** [comment]
I've figured out the issue. It was a value of the targetframework (aspnetcore instead netstandard).

**Comment by CornedBee** [comment]
I would like to reopen this. It's currently broken on preview6 and master. Not only is the file in the wrong location, the ref assembly still refers to the class in the Layouts namespace.

This means that when compiling, it references Layouts.PageDisplay, but at runtime, it can't find that class in the actual assembly.

This was broken by PR #10491.

https://github.com/aspnet/AspNetCore/blob/master/src/Components/Components/ref/Microsoft.AspNetCore.Components.netstandard2.0.Manual.cs#L234

https://github.com/aspnet/AspNetCore/blob/master/src/Components/Components/src/Layouts/PageDisplay.cs#L13
