### ISSUE TITLE
CS1061: 'IApplicationBuilder' does not contain a definition for 'UseAuthorization'

### ISSUE THREAD

**Issue by buckstephenh** [aspnet/AspNetCore#11290]
### Describe the bug
Source/Web/Startup.cs(169,17): error CS1061: 'IApplicationBuilder' does not contain a definition for 'UseAuthorization' and no accessible extension method 'UseAuthorization' accepting a first argument of type 'IApplicationBuilder' could be found (are you missing a using directive or an assembly reference?)

### To Reproduce
1. Using this version of ASP.NET Core 3.0.100-preview6-012264

2. App project builds and runs successfully

3. xunit project that references project fails to build showing CS1061

NOTE: xunit built successfully with 3.0.100-preview5-011568

### Expected behavior

The xunit project build should report that Microsoft.AspNetCore 3.0.0-preview6.19307.2 assets are specified in the project but 3.0.100-preview5-011568 is specified in the global.json file located in the test project folder, which was the source of the error.

**Comment by davidfowl** [comment]
I can't reproduce this. Can you provide a solution that reproduces the issue and the specific environment you're running in with version information? (VS version, VS code version etc)

**Comment by buckstephenh** [comment]
It occurs on command line "dotnet build" OSX.    If the build output would raise the issue that Microsoft.AspNetCore assets (x) are newer than the specified dotnet Core SDK (y) specified in global.json then my eye would have been directed to the real problem instead of the IApplicationBuilder follow-on problem.  I will try to put together a test case.

**Comment by huanbd** [comment]
I catch this error in my project when update from v3-preview5 to v3-preview6.19307.2
My environment:
- Window 10 version 1903
- Visual Studio 2019 Preview, version 16.2.0 Preview 2.0

**Comment by huanbd** [comment]
Hi, Sorry, I've found the cause. I've not yet download and install SDK Net.core preview 6 in my computer 👎
