### ISSUE TITLE
[RazorComponents] Attribute 'Parameter' is not valid on this declaration type.

### ISSUE THREAD

**Issue by roboriaan** [aspnet/AspNetCore#9364]
Hi,

I'm getting the following build error after upgrading VS2019 to 16.1.0 Preview 1.0 by following the recommendation bell icon (bottom right) :

### error CS0592: Attribute 'Parameter' is not valid on this declaration type. It is only valid on 'property, indexer' declarations

I've noticed that the Razor components template option is also missing from the create new project dialog. So to reproduce this issue, upgrade to visual studio to 16.1.0 Preview 1.0 and then create a new Razor components project using the cli "dotnet new razorcomponents".

I have reinstalled the blazor extension but not downgraded vs to the previous version.  

Blazor extension : 16.0.19154.2
VS2019 : 16.1.0 Preview 1.0

TIA

**Comment by dyl10s** [comment]
I also have this issue however the project builds and runs fine.

**Comment by roboriaan** [comment]
Yeah quite strange. Things like OnInitAsync shows no suitable method found for override and there's no reference to RenderFragment. After doing a restart it builds and runs but still shows up as an error. Eh maybe just a tooling issue? 

Just as a test I followed the installation procedure on blazor.net again and got VS 2019 without the preview label (16.0.1). Was very excited but then noticed that the [Parameter] attribute shows up as dead text if that makes sense. Seems vs has no knowledge of what it is but not showing up as an error.

**Comment by roboriaan** [comment]
Seems to be fixed in 16.0.19216.3

**Comment by dyl10s** [comment]
> Seems to be fixed in 16.0.19216.3

Just curious how can I update to this build?

**Comment by roboriaan** [comment]
I followed the instructions here :
https://devblogs.microsoft.com/aspnet/blazor-now-in-official-preview/

There's quite a lot of new goodies in this release. Very excited!
